# MixList Initial query with dummy data

mutation CREATE_MIX_LIST(
  $name: String!
  $tagline: String!
  $authorDisplay: String!
) {
  createMixList(
    newMixList: {
      name: $name
      tagline: $tagline
      authorDisplay: $authorDisplay
    }
  ) {
    name
    authorDisplay
    tagline
  }
}
# Example apollo query variables
# {
# 		"name": "here is a name",
#     "tagline": "hynpotic techno and acid",
#     "authorDisplay": "UserMadeTestMix"
# }		




#Dummy Resolvers
Query: {
    getAllMixes: () =>{
      return [{
        name: "Trance Mix 1",
        authorDisplay: "Sameghosts",
        tagline: "Hot Trance Bangers for the summer"
      }, {
        name: "Illbient 2021",
        authorDisplay: "Differentghosts",
        tagline: "This is a sample headline for illbient mix"
      }]
    }
  },
  Mutation: {
    createMixList: async () => {
      return {
        name: "Trance Mix 1",
        authorDisplay: "Sameghosts",
        tagline: "Hot Trance Bangers for the summer"
      }
    }
  }
  # Dummy apollo
  query GET_ALL_MIXES{
  getAllMixes{
    name
    authorDisplay
    tagline
  }
}

mutation CREATE_MIX_LIST{
  createMixList {
    name
    authorDisplay
    tagline
  }
}
